# Generated by Django 4.1.3 on 2022-12-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('telco', 'Telecommunication'), ('log', 'Logistics'), ('agr', 'Agriculture'), ('aero', 'Aerospace'), ('pharm', 'Pharmaceutical')], max_length=15)),
                ('founded', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
